const serviceService = require("../services/serviceService");

// ✅ GET SERVICES BY USER (citizenId)
exports.getByUser = async (req, res) => {
  try {
    const { userId } = req.params;

    // 1. Validation: Ensure userId exists and is a number
    if (!userId || isNaN(parseInt(userId))) {
      console.error(
        `⚠️ Validation Failed: Invalid User ID received (${userId})`,
      );
      return res.status(400).json({
        success: false,
        error: "A valid numeric User ID is required.",
      });
    }

    console.log(`📡 Fetching services from DB for User ID: ${userId}...`);

    // 2. Call the service layer
    const services = await serviceService.getServicesByUser(userId);

    // 3. Response
    res.status(200).json({
      success: true,
      count: services.length,
      services: services,
    });
  } catch (err) {
    // 4. Detailed Logging: Check your terminal to see the actual SQL error
    console.error("❌ Database Error in getByUser:", err.message);

    res.status(500).json({
      success: false,
      error: "Internal Server Error",
      message: err.message, // This helps you debug in Postman/Flutter
    });
  }
};

exports.create = async (req, res) => {
  try {
    const { userId } = req.params;

    // Log this to your terminal to verify Multer is working
    console.log("📂 Multer File Object:", req.file);

    const service = await serviceService.createService(
      req.body,
      userId,
      req.file, // This contains the filename generated by your middleware
    );

    res.status(201).json({ success: true, service });
  } catch (err) {
    console.error("❌ Controller Error:", err);
    res.status(400).json({ success: false, error: err.message });
  }
};

// ✅ UPDATE SERVICE
exports.update = async (req, res) => {
  try {
    const service = await serviceService.updateService(req.params.id, req.body);
    res.json({ success: true, service });
  } catch (err) {
    console.error("❌ Error in Service Controller (Update):", err);
    res.status(400).json({ success: false, error: err.message });
  }
};

// ✅ GET ALL SERVICES
exports.getAll = async (req, res) => {
  try {
    const services = await serviceService.getAllServices();
    res.json({ success: true, services });
  } catch (err) {
    res.status(500).json({ success: false, error: err.message });
  }
};

// ✅ GET SERVICES BY SERVICE TYPE
exports.getByServiceType = async (req, res) => {
  try {
    const services = await serviceService.getServicesByType(
      req.params.serviceTypeId,
    );
    res.json({ success: true, services });
  } catch (err) {
    res.status(400).json({ success: false, error: err.message });
  }
};

// ✅ DELETE SERVICE
exports.delete = async (req, res) => {
  try {
    await serviceService.deleteService(req.params.id);
    res.json({ success: true, message: "Service deleted successfully" });
  } catch (err) {
    res.status(400).json({ success: false, error: err.message });
  }
};
